import 'package:furpa_merkez_terminal/shared/data/barcode_resolution_models.dart';

BarcodeResolutionResult buildBarcodeResolutionResult({
  String barcode = '8690000000012',
  int warehouseNo = 110,
  String stockCode = '015792',
  String stockName = 'Test Urun',
  String unitName = 'AD',
  double unitMultiplier = 1,
  double salesPrice = 125,
  int priceTypeCode = 0,
  bool isFound = true,
  bool isUsableInOperation = true,
  bool isCaseBarcode = false,
  double? matchedUnitsPerCase,
  bool isVariableWeightBarcode = false,
  double embeddedQuantity = 0,
  String embeddedQuantityUnit = '',
  String operationType = '',
  String screenCode = '',
  bool? isAllowedForTargetWarehouse = true,
  String targetWarehouseReason = '',
  List<String> targetWarehouseModelCodes = const <String>[],
  bool? hasPurchaseRequirement,
  String purchaseRequirementReason = '',
  bool isBlocked = false,
  bool isSalesBlocked = false,
  bool isPassive = false,
  String operationDecision = '',
  List<String> warnings = const <String>[],
  List<String> errors = const <String>[],
}) {
  return BarcodeResolutionResult(
    isFound: isFound,
    barcode: barcode,
    warehouseNo: warehouseNo,
    screenCode: screenCode,
    resolutionSource: 'test',
    stockCode: stockCode,
    stockName: stockName,
    matchedBarcode: barcode,
    primaryBarcode: barcode,
    caseBarcode: isCaseBarcode ? barcode : '',
    unitsPerCase: matchedUnitsPerCase ?? 0,
    matchedUnitPointer: 1,
    matchedUnitName: unitName,
    matchedUnitMultiplier: unitMultiplier,
    isBlocked: isBlocked,
    isSalesBlocked: isSalesBlocked,
    isOrderBlocked: false,
    isGoodsAcceptanceBlocked: false,
    isUsableInScreen: isUsableInOperation,
    usabilityReason: '',
    defaultSupplierCode: '',
    defaultSupplierName: '',
    lookupBarcode: barcode,
    isVariableWeightBarcode: isVariableWeightBarcode,
    embeddedQuantity: embeddedQuantity,
    embeddedQuantityUnit: embeddedQuantityUnit,
    isBarcodeCheckDigitValid: true,
    barcodeKind: isCaseBarcode ? 'case' : 'product',
    isPrimaryBarcode: !isCaseBarcode,
    isCaseBarcode: isCaseBarcode,
    isAlternativeBarcode: false,
    matchedUnitsPerCase: matchedUnitsPerCase,
    operationType: operationType,
    targetWarehouseNo: null,
    isAllowedForTargetWarehouse: isAllowedForTargetWarehouse,
    targetWarehouseReason: targetWarehouseReason,
    productModelCode: '',
    targetWarehouseModelCodes: targetWarehouseModelCodes,
    supplierCode: '',
    hasPurchaseRequirement: hasPurchaseRequirement,
    purchaseRequirementReason: purchaseRequirementReason,
    salesPrice: salesPrice,
    priceTypeCode: priceTypeCode,
    isPassive: isPassive,
    isUsableInOperation: isUsableInOperation,
    operationDecision: operationDecision,
    warnings: warnings,
    errors: errors,
  );
}
